insert into exercise (name, description, push_pull, upper_lower, body_part) values ();


insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Full Reverse Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Incline Hip Thrust	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Incline Reverse Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Lying Hip Thrust	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Reverse Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Reverse Medicine Ball Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Alternating Heel Touch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Bent-Knee Medicine Ball Hip Rotation	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Cable Chop	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Cross Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Cross Crunch w/ Medicine Ball	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Decline Cross Sit-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Decline Sit-Up w/ Twist	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Reverse Cable Chop	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Seated Medicine Ball Twist	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Trunk Rotator	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Front Plank (from knees)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Front Plank (from toes)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Front Plank (tripod - 1 arm and 2 legs or 2 legs and 1 arm)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Side-Plank (from knees)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Side-Plank (hip lift)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Side-Plank (from toes)	'),TRIM('	Core	'),TRIM('	Static	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Ab Cycle	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Kneeling Ab Rollout	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Medicine Ball V-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	V-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Weighted V-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Bent Knee Sit-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Bent-Knee Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Decline Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Decline Sit-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Heel Touch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Sit-Up	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Abs	'),TRIM('	Weighted Crunch	'),TRIM('	Core	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Assisted Pull-Up	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Close-Grip Lat Pulldown	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Inverted Pull-Up	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Lat Pulldown	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Pull-Up	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Reverse-Grip Lat Pullown	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Reverse-Grip Pull-Up	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	V-Bar Pull-Up	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Wide-Grip Lat Pulldown	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Alternating Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Barbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Hammer Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Long Barbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Reverse-Grip Barbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Bent-Over Single-Arm Long Barbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Machine Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	One Arm Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Reverse Incline Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Rope Cable Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Seated Cable Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Seated Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Single-Arm Cable Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Single-Arm Dumbbell Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Single-Arm Lat Pulldown	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Standing Cable Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Standing Single-Arm Cable Row	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Alternating Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Alternating Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Barbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Bicep Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Bottom/Top/Full Curls	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Concentration Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Cross Body Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	EZ-Bar Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Incline Alternating Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Incline Alternating Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Incline Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Incline Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Kneeling Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Lying Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Lying Double Biceps Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Lying High Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Machine Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Overhead Double Biceps Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Overhead Rope Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher Barbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher EZ-Bar Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher Hammer Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Preacher Single-Arm Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Reverse Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Rope Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Seated Alternating Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Seated Alternating Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Seated Dumbbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Seated Hammer Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Single-Arm Barbell Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Single-Arm Cable Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Single-Arm Dumbbell Curl w/ Incline Bench	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Biceps	'),TRIM('	Spider Curl	'),TRIM('	Upper	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Barbell Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Calf Press	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Calf Raise - Seated	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Calf Raise - Standing	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Dumbbell Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Single-Leg Calf Press	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Single-Leg Dumbbell Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Smith Machine Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Seated Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Calves	'),TRIM('	Seated Single-Leg Calf Raise	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Alternating Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Barbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Chest Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Decline Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Decline Smith Machine Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Dumbbell Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Elevated Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Flat Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Alternating Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Barbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Hammer Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Single-Arm Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Smith Machine Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Twisting Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Kneeling Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Machine Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Machine Vertical Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Medicine Ball Crossover Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Single-Arm Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Smith Machine Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Twisting Dumbbell Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Wide-Grip Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Cable Crossover	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Cable Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Decline Dumbbell Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Dumbbell Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	High Cable Crossover	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Cable Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Dumbbell Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Incline Twisting Dumbbell Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Low Cable Crossover	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Pec Deck	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Chest	'),TRIM('	Pec Deck Fly	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Bent-Knee Single-Leg Hip Lift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Elevated Hip Lift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Elevated Single-Leg Hip Lift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Hip Lift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Single-Leg Hip Lift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Deadlift	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Leg Curl	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Lying Alternating Leg Curl	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Lying Leg Curl	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Lying Single-Leg Curl	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Hamstrings	'),TRIM('	Seated Leg Curl	'),TRIM('	Lower	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Diagonal Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Hack Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Reverse Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Side Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Split Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Step-Up	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Barbell Walking Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Diagonal Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Diagonal Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Reverse Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Side Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Split Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Step-Up	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Dumbbell Walking Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Forward Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lateral Barbell Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lateral Barbell Step-Up	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lateral Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lateral Step-Up	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Leg Press	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Lying Machine Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Machine Hack Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Reverse Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Arm Barbell Side Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Arm Dumbbell Side Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Barbell Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Box Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Dumbbell Box Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Dumbbell Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Smith Machine Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Split Squat	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Step-Up	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Walking Lunge	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Alternating Leg Extension	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Leg Extension	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Quads	'),TRIM('	Single-Leg Extension	'),TRIM('	Lower	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Alternating Superman	'),TRIM('	Core	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Back Raise	'),TRIM('	Core	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Quadruped Alternating Superman	'),TRIM('	Core	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Superman	'),TRIM('	Core	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Back	'),TRIM('	Superman Hold	'),TRIM('	Core	'),TRIM('	Pull	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Arnold Dumbbell Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Barbell Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Dumbbell Alternating Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Dumbbell Front Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Dumbbell Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Dumbbell Twisting Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Machine Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Seated Dumbbell Rear Delt Elbow Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Single-Arm Dumbbell Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Smith Machine Shoulder Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Barbell Front Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Bent-Over Cable Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Bent-Over Dumbbell Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Cable Front Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Cable Lateral Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Dumbbell Lateral Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Front Plate Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Kneeling Single-Arm Cable Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Lying Dumbbell External Rotation	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Lying Dumbbell Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Lying Single-Arm Dumbbell Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Pec Deck Real Delt Extensions	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Reverse Incline Dumbbell Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Seated Dumbbell Rear Delt Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Single-Arm Cable Lateral Raise	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Shoulders	'),TRIM('	Cable External Rotation	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Close-Grip Bench Press	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Forward Lean Dips	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Assisted Dips	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Bench Dips	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Diamond Push-Up	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Dips	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Machine Dips	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Decline Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Decline EZ-Bar Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Decline Single Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Decline Single-Arm Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Dumbbell Kickback	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Incline EZ-Bar Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Kneeling Cable Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Leaning Overhead Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Low Cable Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Cable Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying EZ-Bar Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Overhead EZ-Bar Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Reverse EZ-Bar Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Single Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Single-Arm Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Lying Tricep Extensions	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead Dumbbell Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead EZ-Bar Triceps Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead Rope Cable Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead Single Dumbbell Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead Single-Arm Cable Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Overhead Single-Arm Dumbbell Tricep Extension	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Reverse Tricep Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Rope Triceps Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Single-Arm Towel Triceps Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Single-Arm Triceps Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Towel Triceps Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Tricep Extensions	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Tricep Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	Tricep Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));
insert into exercise (body_part, name, upper_lower, push_pull)	values (TRIM('	Triceps	'),TRIM('	V-Bar Tricep Pushdown	'),TRIM('	Upper	'),TRIM('	Push	'));